export const availableSubjects = [
  "Proqramlaşdırma əsasları və alqoritmlər",
  "Verilənlər bazasının layihələndirilməsi və idarə edilməsi",
  "Kompüter şəbəkələri və qəbula təhlükəsizliyi",
  "İnformasiya texnologiyalarına giriş",
  "Fizika və təbiqi mexanika",
  "Süni intellekt və maşın öyrənməsi",
  "Dilçilik nəzəriyyəsi",
  "Azərbaycan dilinin sintaksisi",
  "Tərcümə nəzəriyyəsi",
  "Riyaziyyat təhlili",
  "Diferensial tənliklər",
  "Xətti cəbr",
  "Makroiqtisadiyyat",
  "Mikroiqtisadiyyat",
  "İqtisadi nəzəriyyə",
  "Ümumi fizika",
  "Kvant mexanikası",
  "Molekulyar fizika",
  "Üzvi kimya",
  "Qeyri-üzvi kimya",
  "Analitik kimya",
  "Azərbaycan tarixi",
  "Ümumi tarix",
  "Arxeologiya",
  "Ümumi psixologiya",
  "Şəxsiyyət psixologiyası",
  "Sosial psixologiya",
  "Ümumi biologiya",
  "Genetika",
  "Ekologiya",
  "Konstitusiya hüququ",
  "Cinayət hüququ",
  "Mülki hüquq",
  "Fiziki coğrafiya",
  "İqtisadi coğrafiya",
  "Geomorfologiya",
];
