import type { TeacherDTO } from "@/types/types";

export const teachers: TeacherDTO[] = [
  {
    id: 1,
    avatar:
      "https://images.unsplash.com/photo-1722926323079-0836a07d2340?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Əli",
      surname: "Məmmədov",
      fatherName: "Həsən",
      gender: "Kişi",
      birthDate: "15.05.1975",
      idSeries: "12345567",
      idNumber: "AZE 053539",
      fincode: "2jceyt",
      username: "ali.mammadov",
      citizenship: "Azərbaycan",
      maritalStatus: "Evli",
      socialStatus: "Məcburi köckün",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "12.03.2024",
    },
    contactInformation: {
      mobileNumber: "+994102345678",
      internalNumber: "3445",
      email: "ali.mammadov@example.com",
      address: "C. Məmməquluzadə 102a, Blok 4",
      registrationAddress: "C. Məmməquluzadə 102a, Blok 4",
    },
    academicInformation: {
      department: "Kompüter Şəbəkələri",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Dosent",
      maxHours: 750,
      positionType: "0.5 ştat",
      employmentType: "Saat hesabı",
      languagesTaught: ["Azərbaycan", "Rus", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Proqramlaşdırma əsasları və alqoritmlər",
      "Verilənlər bazasının layihələndirilməsi və idarə edilməsi",
      "Kompüter şəbəkələri və şəbəkə təhlükəsizliyi",
      "Riyazi analiz və diferensial tənliklər",
      "Fizika və tətbiqi mexanika",
      "Süni intellekt və maşın öyrənməsi",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "1MB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1MB" },
      { name: "Sertifikat - İngilis dili B2", type: "Word", size: "1MB" },
    ],
    status: "Əmr yoxdur",
    fullName: "Əli Məmmədov Həsən",
  },
  {
    id: 2,
    avatar:
      "https://images.unsplash.com/photo-1650056200016-70c0cb987ce7?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=837",
    personalInformation: {
      name: "Nigar",
      surname: "Rəhimova",
      fatherName: "Telman",
      gender: "Qadın",
      birthDate: "22.09.1982",
      idSeries: "87654321",
      idNumber: "AZE 124567",
      fincode: "5kmpqr",
      username: "nigar.rahimova",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Evli",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "01.09.2023",
    },
    contactInformation: {
      mobileNumber: "+994505556677",
      internalNumber: "3201",
      email: "nigar.rahimova@example.com",
      address: "Ü. Hacıbəyov 45, Mənzil 12",
      registrationAddress: "Ü. Hacıbəyov 45, Mənzil 12",
    },
    academicInformation: {
      department: "Riyaziyyat",
      academicDegree: "Elmlər doktoru",
      academicTitle: "Professor",
      maxHours: 900,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Xətti cəbr və analitik həndəsə",
      "Ehtimal nəzəriyyəsi və riyazi statistika",
      "Diskret riyaziyyat",
      "Riyazi analiz",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "1.2MB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.1MB" },
      { name: "Doktorluq dissertasiyası", type: "Word", size: "3.5MB" },
      { name: "IELTS sertifikatı", type: "PDF", size: "800KB" },
    ],
    status: "Əmr var",
    fullName: "Nigar Rəhimova Telman",
  },
  {
    id: 3,
    avatar:
      "https://images.unsplash.com/photo-1654110455429-cf322b40a906?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXZhdGFyfGVufDB8MnwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=500",
    personalInformation: {
      name: "Rəşad",
      surname: "Əliyev",
      fatherName: "Mübariz",
      gender: "Kişi",
      birthDate: "10.03.1988",
      idSeries: "23456789",
      idNumber: "AZE 234891",
      fincode: "7xyzab",
      username: "rashad.aliyev",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Subay",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "15.01.2022",
    },
    contactInformation: {
      mobileNumber: "+994557778899",
      internalNumber: "3567",
      email: "rashad.aliyev@example.com",
      address: "N. Nərimanov prospekti 88, Mənzil 25",
      registrationAddress: "N. Nərimanov prospekti 88, Mənzil 25",
    },
    academicInformation: {
      department: "Fizika",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Baş müəllim",
      maxHours: 800,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "Rus"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Ümumi fizika",
      "Kvant mexanikası",
      "Termodinamika və statistik fizika",
      "Elektrodinamika",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "950KB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.1MB" },
      { name: "Dissertasiya", type: "Word", size: "2.8MB" },
    ],
    status: "Əmr var",
    fullName: "Rəşad Əliyev Mübariz",
  },
  {
    id: 4,
    avatar:
      "https://images.unsplash.com/photo-1701615004837-40d8573b6652?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YXZhdGFyfGVufDB8MnwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=500",
    personalInformation: {
      name: "Səbinə",
      surname: "Həsənova",
      fatherName: "Elxan",
      gender: "Qadın",
      birthDate: "05.11.1995",
      idSeries: "34567890",
      idNumber: "AZE 345612",
      fincode: "9abcde",
      username: "sabina.hasanova",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Evli",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "05.09.2021",
    },
    contactInformation: {
      mobileNumber: "+994507778899",
      internalNumber: "3112",
      email: "sabinahasanova@example.com",
      address: "Bakı, İnşaatçılar pr. 25, mənzil 9",
      registrationAddress: "Bakı, İnşaatçılar pr. 25, mənzil 9",
    },
    academicInformation: {
      department: "İngilis dili",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Dosent",
      maxHours: 850,
      positionType: "Saat hesabı",
      employmentType: "Əsas iş",
      languagesTaught: ["İngilis", "Azərbaycan", "Türk"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "İngilis dili qrammatikası",
      "İngilis ədəbiyyatı",
      "Akademik yazı",
      "Tərcümə nəzəriyyəsi və təcrübəsi",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "1MB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.2MB" },
      { name: "TOEFL sertifikatı", type: "PDF", size: "700KB" },
      { name: "Cambridge CPE", type: "PDF", size: "850KB" },
    ],
    status: "Əmr var",
    fullName: "Səbinə Həsənova Elxan",
  },
  {
    id: 5,
    avatar:
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YXZhdGFyfGVufDB8MnwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=500",
    personalInformation: {
      name: "Kamran",
      surname: "Quliyev",
      fatherName: "Ramin",
      gender: "Kişi",
      birthDate: "18.07.1978",
      idSeries: "45678901",
      idNumber: "AZE 456723",
      fincode: "3fghij",
      username: "kamran.quliyev",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Evli",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "10.10.2019",
    },
    contactInformation: {
      mobileNumber: "+994557336699",
      internalNumber: "3402",
      email: "kamranquliyev@example.com",
      address: "Bakı, Z.Əliyeva küçəsi 14",
      registrationAddress: "Bakı, Z.Əliyeva küçəsi 14",
    },
    academicInformation: {
      department: "Kimya",
      academicDegree: "Elmlər doktoru",
      academicTitle: "Professor",
      maxHours: 920,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "Rus", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Ümumi kimya",
      "Üzvi kimya",
      "Analitik kimya",
      "Fiziki kimya",
      "Biokimya",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "1.1MB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.3MB" },
      { name: "Doktorluq dissertasiyası", type: "Word", size: "4.2MB" },
      { name: "Alman dili sertifikatı", type: "PDF", size: "600KB" },
    ],
    status: "Əmr var",
    fullName: "Kamran Quliyev Ramin",
  },
  {
    id: 6,
    avatar:
      "https://images.unsplash.com/photo-1607746882042-944635dfe10e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGF2YXRhcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=500",
    personalInformation: {
      name: "Günay",
      surname: "İsmayılova",
      fatherName: "Cavid",
      gender: "Qadın",
      birthDate: "28.12.1985",
      idSeries: "56789012",
      idNumber: "AZE 567834",
      fincode: "4klmno",
      username: "gunay.ismayilova",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Subay",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "20.11.2020",
    },
    contactInformation: {
      mobileNumber: "+994507771122",
      internalNumber: "3189",
      email: "gunal123@example.com",
      address: "Bakı, Azadlıq pr. 55",
      registrationAddress: "Bakı, Azadlıq pr. 55",
    },
    academicInformation: {
      department: "Tarix",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Dosent",
      maxHours: 780,
      positionType: "0.5 ştat",
      employmentType: "Əlavə iş",
      languagesTaught: ["Azərbaycan"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Azərbaycan tarixi",
      "Ümumi tarix",
      "Dünya mədəniyyəti tarixi",
      "Arxeologiya",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "1MB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.2MB" },
      { name: "Dissertasiya", type: "Word", size: "3MB" },
    ],
    status: "Əmr gözləyir",
    fullName: "Günay İsmayılova Cavid",
  },
  {
    id: 7,
    avatar:
      "https://images.unsplash.com/photo-1654110455429-cf322b40a906?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGF2YXRhcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=500",
    personalInformation: {
      name: "Orxan",
      surname: "Bayramov",
      fatherName: "Sənan",
      gender: "Kişi",
      birthDate: "14.04.1992",
      idSeries: "67890123",
      idNumber: "AZE 678945",
      fincode: "6pqrst",
      username: "orxan.bayramov",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Evli",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "18.02.2020",
    },
    contactInformation: {
      email: "orxanbayramov2@gmail.com",
      mobileNumber: "+994703334455",
      internalNumber: "3876",
      address: "H. Əliyev prospekti 234, Blok 2",
      registrationAddress: "H. Əliyev prospekti 234, Blok 2",
    },
    academicInformation: {
      department: "İqtisadiyyat",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Baş müəllim",
      maxHours: 820,
      positionType: "Saat hesabı",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Mikroiqtisadiyyat",
      "Makroiqtisadiyyat",
      "Maliyyə menecmenti",
      "İqtisadi nəzəriyyə",
      "Beynəlxalq iqtisadiyyat",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "1.1MB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.3MB" },
      { name: "CFA Level 1 sertifikatı", type: "PDF", size: "750KB" },
    ],
    status: "Əmr var",
    fullName: "Orxan Bayramov Sənan",
  },
  {
    id: 8,
    avatar:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YXZhdGFyfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    personalInformation: {
      name: "Leyla",
      surname: "Mustafayeva",
      fatherName: "Akif",
      gender: "Qadın",
      birthDate: "03.08.1983",
      idSeries: "78901234",
      idNumber: "AZE 789056",
      fincode: "8uvwxy",
      username: "leyla.mustafayeva",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Evli",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "09.09.2018",
    },
    contactInformation: {
      mobileNumber: "+994508889900",
      internalNumber: "3098",
      email: "leyla.mustafayeva@example.com",
      address: "M. Müşfiq küçəsi 67, Mənzil 18",
      registrationAddress: "M. Müşfiq küçəsi 67, Mənzil 18",
    },
    academicInformation: {
      department: "Biologiya",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Dosent",
      maxHours: 860,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "Rus"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Ümumi biologiya",
      "Genetika",
      "Molekulyar biologiya",
      "Ekologiya",
      "Botanika",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "1MB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.2MB" },
      { name: "Dissertasiya", type: "Word", size: "3.3MB" },
      { name: "Tədqiqat məqalələri", type: "Word", size: "2.5MB" },
    ],
    status: "Əmr var",
    fullName: "Leyla Mustafayeva Akif",
  },
  {
    id: 9,
    avatar:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Elvin",
      surname: "Nəbiyev",
      fatherName: "Taleh",
      gender: "Kişi",
      birthDate: "25.06.1985",
      idSeries: "89012345",
      idNumber: "AZE 890167",
      fincode: "1zabcd",
      username: "elvin.nabiyev",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Evli",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "05.09.2021",
    },
    contactInformation: {
      email: "elvinnebiyev@gmail.com",
      mobileNumber: "+994559876543",
      internalNumber: "3234",
      address: "Xətai prospekti 189, Blok 6",
      registrationAddress: "Xətai prospekti 189, Blok 6",
    },
    academicInformation: {
      department: "Fəlsəfə",
      academicDegree: "Elmlər doktoru",
      academicTitle: "Professor",
      maxHours: 890,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "Rus", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Fəlsəfə tarixi",
      "Məntiq",
      "Etika",
      "Estetika",
      "Sosial fəlsəfə",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "1.1MB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.2MB" },
      { name: "Doktorluq dissertasiyası", type: "Word", size: "4.5MB" },
      { name: "Monoqrafiya", type: "PDF", size: "5.8MB" },
    ],
    status: "Əmr var",
    fullName: "Elvin Nəbiyev Taleh",
  },
  {
    id: 10,
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXZhdGFyfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=500",
    personalInformation: {
      name: "Aynur",
      surname: "Əhmədova",
      fatherName: "Fərid",
      gender: "Qadın",
      birthDate: "20.01.1991",
      idSeries: "90123456",
      idNumber: "AZE 901278",
      fincode: "2efghi",
      username: "aynur.ahmadova",
      citizenship: "Azərbaycan",
      socialStatus: "-",
      maritalStatus: "Subay",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "01.09.2024",
    },
    contactInformation: {
      email: "aynursddfs@gmail.com",
      mobileNumber: "+994707654321",
      internalNumber: "3465",
      address: "A. Səhhət küçəsi 45, Mənzil 8",
      registrationAddress: "A. Səhhət küçəsi 45, Mənzil 8",
    },
    academicInformation: {
      department: "Psixologiya",
      academicDegree: "-",
      academicTitle: "Müəllim",
      maxHours: 680,
      positionType: "0.5 ştat",
      employmentType: "Saat hesabı",
      languagesTaught: ["Azərbaycan", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Ümumi psixologiya",
      "İnkişaf psixologiyası",
      "Sosial psixologiya",
      "Pedaqoji psixologiya",
    ],
    files: [
      { name: "Bakalavriat diplomu", type: "PDF", size: "980KB" },
      { name: "Magistratura diplomu", type: "PDF", size: "1.1MB" },
      { name: "İngilis dili sertifikatı", type: "PDF", size: "650KB" },
    ],
    status: "Əmr gözləyir",
    fullName: "Aynur Əhmədova Fərid",
  },
];

export const teachersData: TeacherDTO[] = [
  {
    id: 11,
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Rəşad",
      surname: "Məmmədov",
      fatherName: "Elçin",
      gender: "Kişi",
      birthDate: "15.03.1988",
      idSeries: "55667799",
      idNumber: "AZE 234567",
      fincode: "7pqrst",
      username: "rashad.mammadov",
      citizenship: "Azərbaycan",
      maritalStatus: "Evli",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "15.09.2015",
    },
    contactInformation: {
      mobileNumber: "+994552223344",
      internalNumber: "3201",
      email: "rashad.mammadov@example.com",
      address: "Bakı, N. Nərimanov küçəsi 45",
      registrationAddress: "Bakı, N. Nərimanov küçəsi 45",
    },
    academicInformation: {
      department: "Riyaziyyat",
      academicDegree: "Elmlər doktoru",
      academicTitle: "Professor",
      maxHours: 900,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "Rus"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Riyaziyyat təhlili", "Diferensial tənliklər", "Xətti cəbr"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "3.5MB" },
      { name: "Elmi məqalələr toplusu", type: "PDF", size: "5MB" },
      { name: "Pedaqoji sertifikat", type: "PDF", size: "800KB" },
    ],
    status: "Əmr var",
    fullName: "Rəşad Məmmədov Elçin",
  },
  {
    id: 12,
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Səbinə",
      surname: "Əliyeva",
      fatherName: "Ramiz",
      gender: "Qadın",
      birthDate: "22.07.1995",
      idSeries: "66778800",
      idNumber: "AZE 345678",
      fincode: "9uvwxy",
      username: "sabina.aliyeva",
      citizenship: "Azərbaycan",
      maritalStatus: "Subay",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "01.10.2020",
    },
    contactInformation: {
      mobileNumber: "+994705556677",
      internalNumber: "3302",
      email: "sabina.aliyeva@example.com",
      address: "Bakı, Ə. Rəcəbli küçəsi 12",
      registrationAddress: "Bakı, Ə. Rəcəbli küçəsi 12",
    },
    academicInformation: {
      department: "İqtisadiyyat",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "-",
      maxHours: 750,
      positionType: "0.5 Ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Makroiqtisadiyyat", "Mikroiqtisadiyyat", "İqtisadi nəzəriyyə"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "2.3MB" },
      { name: "IELTS sertifikatı", type: "PDF", size: "600KB" },
    ],
    status: "Əmr gözləyir",
    fullName: "Səbinə Əliyeva Ramiz",
  },
  {
    id: 13,
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Fərid",
      surname: "Həsənov",
      fatherName: "Tofiq",
      gender: "Kişi",
      birthDate: "10.01.1990",
      idSeries: "77889911",
      idNumber: "AZE 456789",
      fincode: "2zabcd",
      username: "farid.hasanov",
      citizenship: "Azərbaycan",
      maritalStatus: "Evli",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "20.03.2018",
    },
    contactInformation: {
      mobileNumber: "+994514447788",
      internalNumber: "3403",
      email: "farid.hasanov@example.com",
      address: "Bakı, Ü. Hacıbəyov küçəsi 78",
      registrationAddress: "Bakı, Ü. Hacıbəyov küçəsi 78",
    },
    academicInformation: {
      department: "Fizika",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Baş müəllim",
      maxHours: 820,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Ümumi fizika", "Kvant mexanikası", "Molekulyar fizika"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "4MB" },
      { name: "Tədris proqramları", type: "PDF", size: "1.5MB" },
    ],
    status: "Əmr var",
    fullName: "Fərid Həsənov Tofiq",
  },
  {
    id: 14,
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Aynur",
      surname: "İsmayılova",
      fatherName: "Həsən",
      gender: "Qadın",
      birthDate: "05.05.1992",
      idSeries: "88990022",
      idNumber: "AZE 567890",
      fincode: "4efghi",
      username: "aynur.ismayilova",
      citizenship: "Azərbaycan",
      maritalStatus: "Evli",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "10.09.2019",
    },
    contactInformation: {
      mobileNumber: "+994557778899",
      internalNumber: "3504",
      email: "aynur.ismayilova@example.com",
      address: "Bakı, H. Zərdabi küçəsi 34",
      registrationAddress: "Bakı, H. Zərdabi küçəsi 34",
    },
    academicInformation: {
      department: "Kimya",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Dosent",
      maxHours: 840,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Üzvi kimya", "Qeyri-üzvi kimya", "Analitik kimya"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "3.2MB" },
      { name: "Cambridge sertifikatı", type: "PDF", size: "700KB" },
      { name: "Laboratoriya təlimatları", type: "PDF", size: "2MB" },
    ],
    status: "Əmr var",
    fullName: "Aynur İsmayılova Həsən",
  },
  {
    id: 15,
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Elvin",
      surname: "Quliyev",
      fatherName: "Vüqar",
      gender: "Kişi",
      birthDate: "18.12.1987",
      idSeries: "99001133",
      idNumber: "AZE 678901",
      fincode: "6jklmn",
      username: "elvin.guliyev",
      citizenship: "Azərbaycan",
      maritalStatus: "Evli",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "05.02.2014",
    },
    contactInformation: {
      mobileNumber: "+994708889900",
      internalNumber: "3605",
      email: "elvin.guliyev@example.com",
      address: "Bakı, M. Müşfiq küçəsi 56",
      registrationAddress: "Bakı, M. Müşfiq küçəsi 56",
    },
    academicInformation: {
      department: "Tarix",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Dosent",
      maxHours: 810,
      positionType: "Saat hesabı",
      employmentType: "Əlavə iş",
      languagesTaught: ["Azərbaycan", "Rus", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Azərbaycan tarixi", "Ümumi tarix", "Arxeologiya"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "4.5MB" },
      { name: "Elmi məqalələr", type: "PDF", size: "3MB" },
    ],
    status: "Əmr yoxdur",
    fullName: "Elvin Quliyev Vüqar",
  },
  {
    id: 16,
    avatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Leyla",
      surname: "Cəfərova",
      fatherName: "Əli",
      gender: "Qadın",
      birthDate: "28.08.1994",
      idSeries: "11223344",
      idNumber: "AZE 789012",
      fincode: "8opqrs",
      username: "leyla.cafarova",
      citizenship: "Azərbaycan",
      maritalStatus: "Subay",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "12.11.2021",
    },
    contactInformation: {
      mobileNumber: "+994519990011",
      internalNumber: "3706",
      email: "leyla.cafarova@example.com",
      address: "Bakı, R. Behbudov küçəsi 89",
      registrationAddress: "Bakı, R. Behbudov küçəsi 89",
    },
    academicInformation: {
      department: "Psixologiya",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "-",
      maxHours: 760,
      positionType: "0.5 Ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: [
      "Ümumi psixologiya",
      "Şəxsiyyət psixologiyası",
      "Sosial psixologiya",
    ],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "2.8MB" },
      { name: "TOEFL sertifikatı", type: "PDF", size: "500KB" },
    ],
    status: "Əmr gözləyir",
    fullName: "Leyla Cəfərova Əli",
  },
  {
    id: 17,
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Orxan",
      surname: "Nəbiyev",
      fatherName: "İlham",
      gender: "Kişi",
      birthDate: "14.04.1989",
      idSeries: "22334455",
      idNumber: "AZE 890123",
      fincode: "1tuvwx",
      username: "orxan.nabiyev",
      citizenship: "Azərbaycan",
      maritalStatus: "Evli",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "01.09.2016",
    },
    contactInformation: {
      mobileNumber: "+994551112233",
      internalNumber: "3807",
      email: "orxan.nabiyev@example.com",
      address: "Bakı, A. Səhhət küçəsi 67",
      registrationAddress: "Bakı, A. Səhhət küçəsi 67",
    },
    academicInformation: {
      department: "İnformatika",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Baş müəllim",
      maxHours: 870,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Proqramlaşdırma", "Verilənlər bazası", "Kompüter şəbəkələri"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "3.7MB" },
      { name: "Microsoft sertifikatı", type: "PDF", size: "900KB" },
      { name: "Cisco sertifikatı", type: "PDF", size: "1.2MB" },
    ],
    status: "Əmr var",
    fullName: "Orxan Nəbiyev İlham",
  },
  {
    id: 18,
    avatar:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Nigar",
      surname: "Şərifova",
      fatherName: "Mübariz",
      gender: "Qadın",
      birthDate: "19.06.1991",
      idSeries: "33445566",
      idNumber: "AZE 901234",
      fincode: "3yzabc",
      username: "nigar.sharifova",
      citizenship: "Azərbaycan",
      maritalStatus: "Evli",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "25.01.2020",
    },
    contactInformation: {
      mobileNumber: "+994702223344",
      internalNumber: "3908",
      email: "nigar.sharifova@example.com",
      address: "Bakı, B. Vahabzadə küçəsi 45",
      registrationAddress: "Bakı, B. Vahabzadə küçəsi 45",
    },
    academicInformation: {
      department: "Biologiya",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "Dosent",
      maxHours: 800,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "Rus"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Ümumi biologiya", "Genetika", "Ekologiya"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "3.3MB" },
      { name: "Elmi məqalələr", type: "PDF", size: "2.5MB" },
    ],
    status: "Əmr gözləyir",
    fullName: "Nigar Şərifova Mübariz",
  },
  {
    id: 19,
    avatar:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Tural",
      surname: "Bayramov",
      fatherName: "Əkbər",
      gender: "Kişi",
      birthDate: "07.02.1986",
      idSeries: "44556677",
      idNumber: "AZE 012345",
      fincode: "5defgh",
      username: "tural.bayramov",
      citizenship: "Azərbaycan",
      maritalStatus: "Evli",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Xidmət keçib",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "10.10.2013",
    },
    contactInformation: {
      mobileNumber: "+994513334455",
      internalNumber: "4009",
      email: "tural.bayramov@example.com",
      address: "Bakı, İ. Qayıbov küçəsi 23",
      registrationAddress: "Bakı, İ. Qayıbov küçəsi 23",
    },
    academicInformation: {
      department: "Hüquq",
      academicDegree: "Elmlər doktoru",
      academicTitle: "Professor",
      maxHours: 920,
      positionType: "Tam ştat",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "Rus", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Konstitusiya hüququ", "Cinayət hüququ", "Mülki hüquq"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "5.5MB" },
      { name: "Monoqrafiya", type: "PDF", size: "4MB" },
      { name: "Hüquqi sertifikatlar", type: "PDF", size: "1.5MB" },
    ],
    status: "Əmr var",
    fullName: "Tural Bayramov Əkbər",
  },
  {
    id: 20,
    avatar:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-4.1.0&auto=format&fit=crop&q=80&w=880",
    personalInformation: {
      name: "Əsmər",
      surname: "Qasımova",
      fatherName: "Rəsul",
      gender: "Qadın",
      birthDate: "30.10.1996",
      idSeries: "55667788",
      idNumber: "AZE 123457",
      fincode: "7ijklm",
      username: "asmar.gasimova",
      citizenship: "Azərbaycan",
      maritalStatus: "Subay",
      socialStatus: "-",
      socialCondition: "-",
      militaryStatus: "Yoxdur",
      disabilityStatus: "Yoxdur",
      employmentStartDate: "15.03.2022",
    },
    contactInformation: {
      mobileNumber: "+994554445566",
      internalNumber: "4110",
      email: "asmar.gasimova@example.com",
      address: "Bakı, Ş. Mehdiyev küçəsi 12",
      registrationAddress: "Bakı, Ş. Mehdiyev küçəsi 12",
    },
    academicInformation: {
      department: "Coğrafiya",
      academicDegree: "Fəlsəfə doktoru",
      academicTitle: "-",
      maxHours: 730,
      positionType: "Saat hesabı",
      employmentType: "Əsas iş",
      languagesTaught: ["Azərbaycan", "İngilis"],
      foreignLanguages: ["Azərbaycan", "Rus", "İngilis", "Fransız", "Alman"],
    },
    subjects: ["Fiziki coğrafiya", "İqtisadi coğrafiya", "Geomorfologiya"],
    files: [
      { name: "Dissertasiya", type: "PDF", size: "2.6MB" },
      { name: "İelts sertifikatı", type: "PDF", size: "550KB" },
    ],
    status: "Əmr yoxdur",
    fullName: "Əsmər Qasımova Rəsul",
  },
];
